pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: merge pull requests from dependabot if CI passes
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
